Repository clay/amphora, pull requests merged in 2019-06, with the labels that each got.

#660 Update the main.workflow file to add new action
  .github/main.workflow
  website/siteConfig.js
Labels: docs

#667 Update the actions on main.workflow file
  .github/main.workflow
Labels: blocked, docs

#668 Update the docs and website README
  docs/README.md
  website/README.md
Labels: docs

#669 Add the missing route information
  docs/routes.md
  docs/routing.md
  website/sidebars.json
Labels: docs

#578 Changing circle flow
  .circleci/config.yml
Labels: maintenance
